# Generated by Django 3.1.2 on 2021-04-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210424_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacherId',
            field=models.CharField(blank=True, default='HIC-0000', max_length=8, null=True),
        ),
    ]
