# Generated by Django 3.1.2 on 2021-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210426_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='empId',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='empId',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
