# Generated by Django 3.1.2 on 2021-04-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210426_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('id',)},
        ),
    ]
