# Generated by Django 4.1 on 2023-09-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0014_accountant_nssf_number_accountant_tin_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='alt_email',
            field=models.EmailField(blank=True, help_text='Personal Email apart from the one given by the school', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Teacher_images'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='national_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_specialization',
            field=models.ManyToManyField(blank=True, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
