# Generated by Django 4.1 on 2023-09-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_teachersattendance_teacher_and_more'),
        ('administration', '0015_alter_classteacher_unique_together_and_more'),
        ('users', '0016_alter_accountant_options_remove_accountant_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
