# Generated by Django 4.1 on 2023-09-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageToTeacher',
        ),
    ]
