# Generated by Django 3.1.2 on 2021-04-22 18:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(help_text='User agent. We can use this to determine operating system and browser in use.', max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('ip', models.GenericIPAddressField()),
                ('usage', models.CharField(max_length=255)),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
