# Generated by Django 3.1.2 on 2021-04-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0003_auto_20210424_2015'),
        ('users', '0002_auto_20210424_1320'),
        ('administration', '0002_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Class Name')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Grade Number')),
                ('shortname', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('classLevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.classlevel')),
                ('students', models.ManyToManyField(blank=True, null=True, to='sis.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.classsection')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'class_section')},
            },
        ),
        migrations.AddField(
            model_name='classsection',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.classteacher'),
        ),
    ]
