# Generated by Django 3.1.2 on 2021-04-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0003_auto_20210424_2015'),
        ('administration', '0003_auto_20210426_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='students',
            field=models.ManyToManyField(blank=True, to='sis.Student'),
        ),
    ]
