# Generated by Django 3.1.2 on 2021-04-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_auto_20210427_1558'),
        ('administration', '0004_auto_20210426_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='classLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis.classlevel'),
        ),
        migrations.DeleteModel(
            name='ClassLevel',
        ),
    ]
