# Generated by Django 3.1.2 on 2021-05-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20210427_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsection',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classsection',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
