# Generated by Django 3.1.2 on 2021-05-19 12:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_period_taught'),
        ('sis', '0007_auto_20210503_0654'),
        ('administration', '0006_auto_20210503_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('absent_students', models.ManyToManyField(to='sis.Student')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.classsection')),
                ('periods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.dailytimetable')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
