# Generated by Django 3.1.8 on 2022-05-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20210626_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
