# Generated by Django 4.1 on 2023-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_accesslog_date_alter_accesslog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
