# Generated by Django 4.1 on 2023-09-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_alter_accesslog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('graduation_date', models.DateField(blank=True, help_text='The date when students graduate', null=True)),
                ('active_year', models.BooleanField(help_text='DANGER!! This is the current school year. There can only be one and setting this will remove it from other years. If you want to change the active year you almost certainly want to click Admin, Change School Year.')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1, unique=True)),
            ],
            options={
                'ordering': ('day',),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='DANGER..!!!! If marked this will be the default School Information System Wide...')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('school_type', models.CharField(blank=True, choices=[('boarding school', 'boarding school'), ('day school', 'day school'), ('boarding-day school', 'boarding-day school')], max_length=25, null=True)),
                ('students_gender', models.CharField(blank=True, choices=[('Boys School', 'Boys School'), ('Girl School', 'Girl School'), ('Mixed', 'Mixed')], max_length=25, null=True)),
                ('ownership', models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private')], max_length=25, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('school_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_info')),
            ],
        ),
        migrations.DeleteModel(
            name='ClassJournal',
        ),
    ]
