# Generated by Django 3.1.2 on 2020-10-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=20, null=True)),
                ('middleName', models.CharField(blank=True, max_length=20, null=True)),
                ('lastName', models.CharField(blank=True, max_length=20, null=True)),
                ('birthDate', models.DateField()),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('parentPhone', models.CharField(blank=True, max_length=12, null=True)),
                ('classLevel', models.CharField(blank=True, choices=[('Form One', 'Form One'), ('Form Two', 'Form Two'), ('Form Three', 'Form Three'), ('Form Four', 'Form Four')], max_length=10, null=True)),
                ('stream', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
