# Generated by Django 3.1.8 on 2021-12-14 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_teacher_short_name'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('abbr', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('paid_to', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.accountant')),
                ('paid_for', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.paymentallocation')),
            ],
        ),
    ]
