# Generated by Django 3.1.8 on 2021-12-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20211214_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no',
            field=models.IntegerField(unique=True),
        ),
    ]
