# Generated by Django 4.1 on 2022-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_allocation_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
