# Generated by Django 4.1 on 2022-10-18 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_accountant_id_alter_customuser_id_and_more'),
        ('finance', '0007_alter_payment_paid_to_alter_receipt_paid_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.accountant'),
        ),
    ]
