# Generated by Django 4.1 on 2022-11-27 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_accountant_id_alter_customuser_id_and_more'),
        ('sis', '0012_remove_student_grad_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_alter_receipt_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.accountant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentallocation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='paid_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.allocation'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.accountant'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.student'),
        ),
    ]
