# Generated by Django 4.1 on 2023-08-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_allocation_name_alter_payment_paid_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allocation',
            new_name='ReceiptAllocation',
        ),
    ]
