# Generated by Django 4.1 on 2023-09-23 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_classyear_dormitory_examinationlisthandler_and_more'),
        ('finance', '0010_rename_allocation_receiptallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.student'),
        ),
    ]
