from django.contrib import admin

from .models import *

admin.site.register(Department)
admin.site.register(Subject)
admin.site.register(GradeLevel)
admin.site.register(ClassLevel)
admin.site.register(ClassYear)
admin.site.register(ReasonLeft)
admin.site.register(Stream)
admin.site.register(ClassRoom)
admin.site.register(SubjectAllocation)
admin.site.register(StudentClass)
admin.site.register(StudentsMedicalHistory)
admin.site.register(StudentsPreviousAcademicHistory)
admin.site.register(GradeScale)
admin.site.register(GradeScaleRule)
admin.site.register(Result)
admin.site.register(Dormitory)
admin.site.register(DormitoryAllocation)
admin.site.register(ExaminationListHandler)
admin.site.register(MarksManagement)
admin.site.register(StudentFile)
admin.site.register(StudentHealthRecord)
admin.site.register(MessageToParent)
admin.site.register(FamilyAccessUser)
admin.site.register(MessageToTeacher)
admin.site.register(Parent)
admin.site.register(Student)
admin.site.register(Teacher)
