# Generated by Django 3.1.2 on 2021-04-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='CarouselImage',
        ),
        migrations.DeleteModel(
            name='DispensaryImage',
        ),
        migrations.DeleteModel(
            name='NurseryImage',
        ),
        migrations.DeleteModel(
            name='PrimaryImage',
        ),
        migrations.DeleteModel(
            name='SecondaryImage',
        ),
    ]
