# Generated by Django 3.1.8 on 2021-06-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210617_0839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOfSpecificExplanations',
            new_name='SpecificExplanations',
        ),
    ]
