# Generated by Django 3.1.8 on 2021-06-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210617_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='list_of_explanations',
            field=models.ManyToManyField(blank=True, to='notes.SpecificExplanations'),
        ),
        migrations.AlterField(
            model_name='note',
            name='notes',
            field=models.ManyToManyField(blank=True, to='notes.Concept'),
        ),
        migrations.AlterField(
            model_name='specificexplanations',
            name='examples',
            field=models.ManyToManyField(blank=True, to='notes.Question'),
        ),
    ]
