# Generated by Django 4.1 on 2023-09-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order_rank', models.IntegerField(blank=True, help_text='Rank that courses will show up in reports', null=True)),
            ],
            options={
                'ordering': ('order_rank', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_selectable', models.BooleanField(default=False, help_text='select if subject is optional')),
                ('graded', models.BooleanField(default=True, help_text='Teachers can submit grades for this course')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(blank=True, help_text='the department associated with this subject', null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.department')),
            ],
        ),
    ]
