# Generated by Django 4.0 on 2023-10-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_parent_username_alter_parent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Christian', 'Christian'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
