# Generated by Django 4.1 on 2023-09-23 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_classyear_dormitory_examinationlisthandler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='This message will be shown to teachers when they log in.')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='If blank the message will be posted starting today')),
                ('end_date', models.DateField(default=django.utils.timezone.now, help_text='if blank the message will end today')),
            ],
        ),
    ]
