# Generated by Django 4.0 on 2023-10-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_student_middle_name_alter_student_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Christian', 'Christian'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
