# Generated by Django 4.0 on 2023-10-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_student_region_alter_student_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(help_text='personal phone number', max_length=150, unique=True),
        ),
    ]
