# Generated by Django 4.0 on 2023-10-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_student_parent_contact_alter_parent_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=10, null=True),
        ),
    ]
