# Generated by Django 3.1.8 on 2022-01-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_auto_20210503_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('addmission_number', 'first_name', 'last_name'), 'permissions': (('viewStudent', 'View student'), ('reports', 'View reports'))},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='bday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='pic',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mname',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='std_vii_number',
            field=models.CharField(blank=True, help_text='For integration with outside databases', max_length=15, null=True, unique=True),
        ),
    ]
