# Generated by Django 3.1.8 on 2022-01-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0008_auto_20220120_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ('primary_contact', 'last_name'), 'verbose_name': 'Student Contact'},
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='mname',
            new_name='middle_name',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
