# Generated by Django 4.1 on 2022-09-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0010_alter_classyear_id_alter_emergencycontact_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='state',
            new_name='region',
        ),
    ]
