# Generated by Django 4.1 on 2022-11-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0011_rename_state_student_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grad_date',
        ),
    ]
