# Generated by Django 4.1 on 2023-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0012_remove_student_grad_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontactnumber',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='emergencycontactnumber',
            name='phonenumber_ptr',
        ),
        migrations.DeleteModel(
            name='MessageToStudent',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contacts',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_guardian',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='EmergencyContactNumber',
        ),
        migrations.DeleteModel(
            name='GradeLevel',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
