# Generated by Django 4.1 on 2023-09-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_classyear_dormitory_examinationlisthandler_and_more'),
        ('finance', '0011_alter_receipt_student'),
        ('notes', '0010_alter_gradedassignment_student_alter_topic__class'),
        ('sis', '0013_remove_emergencycontactnumber_contact_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradescalerule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gradescalerule',
            name='grade_scale',
        ),
        migrations.DeleteModel(
            name='SchoolYear',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_of_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='siblings',
        ),
        migrations.RemoveField(
            model_name='studenthealthrecord',
            name='student',
        ),
        migrations.DeleteModel(
            name='ClassLevel',
        ),
        migrations.DeleteModel(
            name='ClassYear',
        ),
        migrations.DeleteModel(
            name='GradeScale',
        ),
        migrations.DeleteModel(
            name='GradeScaleRule',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentHealthRecord',
        ),
    ]
