# Generated by Django 3.1.2 on 2021-05-03 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20210426_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='schedule.dailytimetable')),
                ('monday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='schedule.dailytimetable')),
                ('saturday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='schedule.dailytimetable')),
                ('thursday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='schedule.dailytimetable')),
                ('tuesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='schedule.dailytimetable')),
                ('wednesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='schedule.dailytimetable')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='schedule.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period1', to='schedule.period'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period2', to='schedule.period'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period3', to='schedule.period'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period4', to='schedule.period'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period5',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period5', to='schedule.period'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period6',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period6', to='schedule.period'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period7',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period7', to='schedule.period'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period8',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period8', to='schedule.period'),
        ),
    ]
