# Generated by Django 3.1.2 on 2021-05-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
