# Generated by Django 3.1.2 on 2021-05-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210503_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ('period_time',)},
        ),
        migrations.RemoveField(
            model_name='period',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='period',
            name='start_time',
        ),
        migrations.AddField(
            model_name='period',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='period_time',
            field=models.CharField(blank=True, choices=[('1', '07:20:00 - 08:00:00'), ('2', '08:00:00 - 08:40:00'), ('3', '08:40:00 - 09:20:00'), ('4', '09:20:00 - 10:00:00'), ('5', '10:20:00 - 11:00:00'), ('6', '11:00:00 - 11:40:00'), ('7', '11:40:00 - 12:20:00'), ('8', '12:20:00 - 13:00:00')], max_length=100, null=True),
        ),
    ]
