# Generated by Django 3.1.2 on 2021-05-03 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210503_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytimetable',
            name='period1',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='period1', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period2',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='period2', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period3',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='period3', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period4',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='period4', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period5',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='period5', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period6',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='period6', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period7',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='period7', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period8',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='period8', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='weeklytimetable',
            name='friday',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='schedule.dailytimetable'),
        ),
        migrations.AlterField(
            model_name='weeklytimetable',
            name='monday',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='schedule.dailytimetable'),
        ),
        migrations.AlterField(
            model_name='weeklytimetable',
            name='saturday',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='schedule.dailytimetable'),
        ),
        migrations.AlterField(
            model_name='weeklytimetable',
            name='thursday',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='schedule.dailytimetable'),
        ),
        migrations.AlterField(
            model_name='weeklytimetable',
            name='tuesday',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='schedule.dailytimetable'),
        ),
        migrations.AlterField(
            model_name='weeklytimetable',
            name='wednesday',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='schedule.dailytimetable'),
        ),
    ]
