# Generated by Django 3.1.2 on 2021-05-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20210503_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='name',
            new_name='subject',
        ),
    ]
