# Generated by Django 3.1.2 on 2021-05-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_auto_20210503_0654'),
        ('schedule', '0012_auto_20210507_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='_class',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sis.classlevel'),
        ),
    ]
