# Generated by Django 3.1.2 on 2021-05-07 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_period__class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytimetable',
            name='period1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period1', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period2', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period3', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period4', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period5', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period6', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period7', to='schedule.period'),
        ),
        migrations.AlterField(
            model_name='dailytimetable',
            name='period8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period8', to='schedule.period'),
        ),
    ]
