# Generated by Django 3.1.2 on 2021-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20210507_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='taught',
            field=models.BooleanField(default=False),
        ),
    ]
