# Generated by Django 5.1 on 2025-01-16 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='administrat_name_c974a6_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['active'], name='administrat_active_1f2ae9_idx'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='administration.academicyear'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['login'], name='administrat_login_i_b9be62_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['date'], name='administrat_date_0e2943_idx'),
        ),
    ]
