# Generated by Django 5.1 on 2025-01-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='default_term_fee',
            field=models.DecimalField(decimal_places=2, default=312500, max_digits=10),
        ),
    ]
