# Generated by Django 5.1 on 2025-01-16 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concept',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.subtopic'),
        ),
        migrations.AddField(
            model_name='gradedassignment',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.assignment'),
        ),
        migrations.AddField(
            model_name='gradedassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student'),
        ),
        migrations.AddField(
            model_name='note',
            name='notes',
            field=models.ManyToManyField(blank=True, to='notes.concept'),
        ),
        migrations.AddField(
            model_name='note',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.subtopic'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='notes.choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='notes.assignment'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(to='notes.choice'),
        ),
        migrations.AddField(
            model_name='specificexplanations',
            name='examples',
            field=models.ManyToManyField(blank=True, to='notes.question'),
        ),
        migrations.AddField(
            model_name='specificexplanations',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.subtopic'),
        ),
        migrations.AddField(
            model_name='concept',
            name='list_of_explanations',
            field=models.ManyToManyField(blank=True, to='notes.specificexplanations'),
        ),
    ]
