# Generated by Django 5.1 on 2025-01-16 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_periods', models.IntegerField(help_text='Total number of periods per week.')),
                ('max_daily_periods', models.IntegerField(default=2, help_text='Maximum number of periods allowed per day for this subject.')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.academicyear')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_subjects', to='academic.subject')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.teacher')),
                ('term', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term')),
            ],
        ),
        migrations.DeleteModel(
            name='SubjectAllocation',
        ),
    ]
