# Generated by Django 5.1 on 2025-01-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_classroom_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='class_room',
        ),
        migrations.AddField(
            model_name='topic',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.classlevel'),
        ),
        migrations.AlterField(
            model_name='department',
            name='order_rank',
            field=models.IntegerField(blank=True, help_text='Rank for subject reports', null=True),
        ),
    ]
