# Generated by Django 5.1 on 2025-01-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_subject_options_remove_topic_class_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='student_id',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='academic.student'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='academic.classroom'),
        ),
    ]
