# Generated by Django 5.1 on 2025-02-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_parent_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('id', 'first_name', 'last_name')},
        ),
    ]
