# Generated by Django 5.1 on 2025-04-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_subject_options_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['admission_number', 'last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='isTeacher',
        ),
    ]
