# Generated by Django 3.1.2 on 2021-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancestatus',
            name='tardy',
        ),
        migrations.AddField(
            model_name='attendancestatus',
            name='late',
            field=models.BooleanField(default=False, help_text='Some statistics need to add various types of late statuses, such as the number in parentheses in daily attendance.'),
        ),
    ]
