# Generated by Django 3.1.2 on 2021-05-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210426_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersattendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachersattendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
