# Generated by Django 4.1 on 2023-09-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_classroom_gradelevel_stream_teacher_and_more'),
        ('attendance', '0005_alter_attendancestatus_id_alter_studentattendance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersattendance',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='academic.teacher'),
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
